fix: support both formats of default profile
this makes it possible for the plugin to interact with chinmina, with and without profile support

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -92,10 +92,12 @@ git_config_add "credential.https://github.com.usehttppath" "true"
 
 # iterate over all provided profiles and configure a credential helper for each one
 for profile in "${profiles[@]}"; do
-  if [[ "${profile}" != org:* && "${profile}" != repo:* ]]; then
-    echo "~~~ :error: Invalid profile: ${profile}. Must start with 'org:' or 'repo:'"
-    exit 1
-  fi
+  # support both the old and new default profile name
+  # TODO: uncomment the below code once chinmina profile support is rolled out
+  # if [[ "${profile}" != org:* && "${profile}" != repo:* ]]; then
+  #   echo "~~~ :error: Invalid profile: ${profile}. Must start with 'org:' or 'repo:'"
+  #   exit 1
+  # fi
   git_config_add "credential.https://github.com.helper" "${plugin_root}/credential-helper/buildkite-connector-credential-helper ${chinmina_url} ${audience} ${profile}"
 done
 
