feat: add profile config support (#4)
* feat: add profile config support

* fix: profiles now configures multiple credential helpers

* fix: cache buildkite oidc token per job

* chore: add profile prefix

* fix: use array over string for profiles argument

* fix: support both formats of default profile

this makes it possible for the plugin to interact with chinmina, with and without profile support

---------

Co-authored-by: Nicholas Tucker <nick.tucker2011@gmail.com>

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -4,6 +4,29 @@ set -euo pipefail
 original_prefix="BUILDKITE_PLUGIN_GITHUB_APP_AUTH_"
 prefix="BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_"
 
+# Reads either a value or a list from plugin config into a global result array
+# Returns success if values were read
+# Inspired by: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/4ac4d6d/lib/shared.bash#L69-L87
+plugin_read_list_into_result() {
+  local prefix="$1"
+  local parameter="${prefix}_0"
+  result=()
+
+  if [[ -n "${!parameter:-}" ]]; then
+    local i=0
+    local parameter="${prefix}_${i}"
+    while [[ -n "${!parameter:-}" ]]; do
+      result+=("${!parameter}")
+      i=$((i+1))
+      parameter="${prefix}_${i}"
+    done
+  elif [[ -n "${!prefix:-}" ]]; then
+    result+=("${!prefix}")
+  fi
+
+  [[ ${#result[@]} -gt 0 ]] || return 1
+}
+
 get_parameter() {
   local key="$1"
   local name="${prefix}${key}"
@@ -32,6 +55,16 @@ if [ -z "$audience" ]; then
   audience="chinmina:default"
 fi
 
+profiles=()
+# read profiles from the plugin config, returns an array
+if plugin_read_list_into_result "${prefix}PROFILES"; then
+  profiles=("${result[@]}")
+fi
+
+if [[ ${#profiles[@]} -eq 0 ]]; then
+  profiles=("repo:default")
+fi
+
 echo "~~~ :git: :github: Configuring Git to authenticate via Chinmina"
 
 plugin_root="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd)"
@@ -56,4 +89,15 @@ git_config_add() {
 }
 
 git_config_add "credential.https://github.com.usehttppath" "true"
-git_config_add "credential.https://github.com.helper" "${plugin_root}/credential-helper/buildkite-connector-credential-helper ${chinmina_url} ${audience}"
+
+# iterate over all provided profiles and configure a credential helper for each one
+for profile in "${profiles[@]}"; do
+  # support both the old and new default profile name
+  # TODO: uncomment the below code once chinmina profile support is rolled out
+  # if [[ "${profile}" != org:* && "${profile}" != repo:* ]]; then
+  #   echo "~~~ :error: Invalid profile: ${profile}. Must start with 'org:' or 'repo:'"
+  #   exit 1
+  # fi
+  git_config_add "credential.https://github.com.helper" "${plugin_root}/credential-helper/buildkite-connector-credential-helper ${chinmina_url} ${audience} ${profile}"
+done
+
