feat: move and rename plugin
Moving to Chinmina organization and being renamed to show the close ties to the bridge. It's not authenticating with GH auth so much as Chinmina.

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -1,10 +1,34 @@
 #!/bin/bash
 set -euo pipefail
 
-vendor_url="${BUILDKITE_PLUGIN_GITHUB_APP_AUTH_VENDOR_URL:?vendor-url property required}"
-audience="${BUILDKITE_PLUGIN_GITHUB_APP_AUTH_AUDIENCE:-github-app-auth:default}"
+original_prefix="BUILDKITE_PLUGIN_GITHUB_APP_AUTH_"
+prefix="BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_"
 
-echo "~~~ :git: :github: Configuring git to authenticate via the vendor agent"
+get_parameter() {
+  local key="$1"
+  local name="${prefix}${key}"
+  local value="${!name:-}"
+
+  if [ -z "$value" ]; then
+    name="${original_prefix}${key}"
+    value="${!name:-}"
+  fi
+  echo "${value}"
+}
+
+vendor_url="$(get_parameter "VENDOR_URL")"
+audience="$(get_parameter "AUDIENCE")"
+
+if [ -z "$vendor_url" ]; then
+  echo "~~~ :error: Missing required parameter vendor-url"
+  exit 1
+fi
+
+if [ -z "$audience" ]; then
+  audience="chinmina:default"
+fi
+
+echo "~~~ :git: :github: Configuring Git to authenticate via Chinmina"
 
 plugin_root="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd)"
 
